# Generated by Django 4.2.28 on 2026-04-08 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Title',
        ),
    ]
